### ISSUE TITLE
Parent graphs can be deinited while a child graph is still alive

### ISSUE THREAD

**Issue by holmes** [square/Cleanse#42]
This crashes the app pretty hard at `Graph.swift#280` where `let `self` = self!`

**Comment by SunnyDayDev** [comment]
I have got the same issue. I will try to gather information how to reproduce it. May be you know how do it better?

**Comment by holmes** [comment]
I haven't looked at this in a long time. If you can repro on a small project we can take another look.

**Comment by sebastianv1** [comment]
Closing because this issue hasn't received any activity lately, feel free to reopen if it's still an issue.

**Comment by SunnyDayDev** [comment]
I've created the project which reproduce the issue:

**Comment by sebastianv1** [comment]
Thanks for the repo project! Will likely take a look this weekend or early next week.

**Comment by sebastianv1** [comment]
@SunnyDayDev It appears the root of the issue is using a `PropertyInjector` type as the Root object. Using a `UIViewController` or `UIWindow` type for the root does not deinit the graphs. 
So in the sample project, in `AppComponent.swift`, we could instead set the `Root` type as:
`typealias Root = UIWindow`.

I'll keep digging how to make the `PropertyInjector` retain an instance to subgraphs.

**Comment by sebastianv1** [comment]
PR to resolve (#122). PTAL!
