### ISSUE TITLE
Sharing "Singleton" across scope and object graph

### ISSUE THREAD

**Issue by startupthekid** [square/Cleanse#70]
Given these two root components with the following scope:

```swift
struct ViewScope: Scope {}
typealias ViewBinder = Binder<ViewScope>

extension FirstViewController {
    struct Component: RootComponent {

        typealias Root = FirstViewController
        typealias Seed = Void
        typealias Scope = ViewScope

        static func configure(binder: ViewBinder) {
            binder.include(module: ViewModule.self)
        }

        static func configureRoot(binder bind: ReceiptBinder<Root>) -> BindingReceipt<Root> {
            return bind.to1(factory: FirstViewController.init(videoView:)
        }
    }
}
extension SecondViewController {
    struct Component: RootComponent {

        typealias Root = SecondViewController
        typealias Seed = Void
        typealias Scope = ViewScope

        static func configure(binder: ViewBinder) {
            binder.include(module: ViewModule.self)
        }

        static func configureRoot(binder bind: ReceiptBinder<Root>) -> BindingReceipt<Root> {
            return bind.to1(factory: SecondViewController.init(videoView:)
        }
    }
}

```

where `ViewModule` looks like:

```swift
struct ViewModule: Module {
    static func configure(_ binder: ViewBinder) {
        binder
            // some view class like a video view that should be a singleton object
            .bind(SomeCustomVideoPlayerAVFoundationView.self)
            .sharedInScope()
            .to0(factory: SomeCustomVideoPlayerAVFoundationView.init)
    }
}
```

it would seem that if I built instances of `FirstViewController` and `SecondViewController` that the `videoView` property on both would refer to the same instance. That doesn't seem to be the case though, it looks like singletons or objects created via `sharedInScope` are restricted not just to scope but also to the object graph that's associated with the root component. That would make sense; I'm creating two new and distinct graphs when I create two separate root components.

The question really is, how do I share object graphs between root components? `Graph` has a `init(scope:parent:)` but that's an internal class. Does a public mechanism exist to do that?

Tangentially related: how do you build `Component` (vs `RootComponent`)? Both are defined as empty protocols conforming to `ComponentBase` but only `RootComponent` can be built directly using `ComponentFactory`. In that case, is `Component` useful? It seems in the case that I would `binder.install(SomeComponent.self)` that I would just make it a module and include it.

**Comment by sebastianv1** [comment]
Sorry for the late reply, we're cleaning up all issues and this definitely isn't a stale issue. :) 

I don't think there's a way to share scopes across `RootComponent` types. Since each one creates its own `Graph` instance there isn't a way to share that same binding. Ideally, there should only be one `RootComponent` in your app which represents very root node of your dependency graph. In the case you describe, I would bind `SomeCustomVideoPlayerAVFoundationView` into the `RootComponent` and create two subcomponents that inject your `SomeCustomVideoPlayerAVFoundationView` instance.

I've recently updated the README docs to hopefully make things more clear (feel free to call out parts that are confusing, I'd like to make them as transparent and easy to use as possible), but creating a `RootComponent` is built using the `ComponentFactory.of(:)` method, and subcomponents can be built by injecting an instance of `ComonentFactory<YourComponent>` into whichever class intends on building the subcomponent. A `ComponentFactory` instance is created for you by installing the subcomponents dependency into your root object. For example:
```swift
static func configure(binder: ViewBinder) {
    binder.install(dependency: SubComponentA.self)
}
```

And then when you want to build that subcomponent, you can inject:
```swift
struct SomeRootObject {
    let subcomponent: ComponentFactory<SubComponent>
    
    func run() {
        let _ = subcomponent.build(())
    }
}```
